version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    REACT_APP_API_SERVICE_URL: "arn:aws:elasticloadbalancing:us-east-1:328489637624:loadbalancer/app/flask-react-alb/91d52a260d610208"

phases:
  pre_build:
    commands:
      - echo logging in to ecr...
      - >
        aws ecr get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin 328489637624.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo building images...
      - >
        docker build \
          -f services/users/Dockerfile.prod \
          -t 328489637624.dkr.ecr.us-east-1.amazonaws.com/thiago-test-driven-users:prod \
          ./services/users
      - >
        docker build \
          -f services/client/Dockerfile.prod \
          -t 328489637624.dkr.ecr.us-east-1.amazonaws.com/thiago-test-driven-client:prod \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_API_SERVICE_URL=http://localhost:5004 \
          ./services/client
      - >
        docker build \
          --target builder \
          --cache-from 328489637624.dkr.ecr.us-east-1.amazonaws.com/thiago-test-driven-client:builder \
          -f services/client/Dockerfile.prod \
          -t 328489637624.dkr.ecr.us-east-1.amazonaws.com/thiago-test-driven-client:builder \
          --build-arg NODE_ENV=production \
          --build-arg REACT_APP_API_SERVICE_URL=http://localhost:5004 \
          ./services/client

  post_build:
    commands:
    - docker push 328489637624.dkr.ecr.us-east-1.amazonaws.com/thiago-test-driven-users:prod
    - docker push 328489637624.dkr.ecr.us-east-1.amazonaws.com/thiago-test-driven-client:prod
    - docker push 328489637624.dkr.ecr.us-east-1.amazonaws.com/thiago-test-driven-client:builder